# Generated by Django 2.1.5 on 2019-11-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_name', models.CharField(max_length=100)),
                ('room', models.IntegerField()),
                ('floor', models.IntegerField()),
            ],
        ),
    ]
