# Generated by Django 2.1.5 on 2019-11-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='beacon_order',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='beacon',
            name='floor',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='beacon',
            name='room',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
