# Generated by Django 2.1.5 on 2019-11-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name_plural': 'Results'},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
