# Generated by Django 2.1.5 on 2019-11-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal_sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_num', models.CharField(default='admin', max_length=20)),
                ('bssid', models.CharField(max_length=30)),
                ('signal_strength', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Signal Sort',
            },
        ),
    ]
