# Generated by Django 2.1.5 on 2019-11-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker_register',
            old_name='new_tracker_number',
            new_name='tracker_number',
        ),
    ]
