# Generated by Django 2.1.5 on 2019-11-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_registration', '0002_auto_20191106_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracker_register',
            options={'verbose_name_plural': 'Register'},
        ),
    ]
