# Generated by Django 2.1.5 on 2019-11-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorted',
            options={'verbose_name_plural': 'Sorted Data'},
        ),
    ]
